### PR TITLE
Spinning token 🤘

### PR DESCRIPTION
**Pull request by vidvidvid**
Added the spinning version of the token which was created by beti.

https://user-images.githubusercontent.com/35112939/191697206-ba36cf57-5d21-4496-92a1-ab9d072787db.mov

### CODE REVIEW

**Comment by coltraneyan** [comment]
lgtm

**Comment by MantisClone** [comment]
LGTM as well.

**Comment by vidvidvid** [comment]
Just waiting for BMO to polish the 3d token with the new logo. He posted it into the commons char today, i think

**Comment by jeffreywdonahue** [comment]
looks great

**Comment by MantisClone** [comment]
The new token looks great!

image

**Pull request closed without merging**
